title: Litany of Horror
description: Stories from the edge of faith.
url: "https://fearfulsmtry.github.io"
baseurl: "/litany-of-horror"

# Social media usernames (without @ symbol)
author:
  name: Kris Canasa
  email: your-email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
future: true

# Sidebar configuration
sidebar_home_link: true

# Custom vars
version: 1.0.0

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
